// Copyright (c) Microsoft. All rights reserved.

const lang = {
	"ACKNOWLEDGE": "Reconnaître",
	"ACKNOWLEDGED": "Reconnu",
	"ACTIONS": "actes",
	"ACTONDEVICES": "Agir sur les appareils",
	"ADD": "Ajouter",
	"ADDCONDITIONS": "Ajouter des conditions",
	"ADDDEVICES": "+ Provision",
	"ADD_TAG": "Ajouter une étiquette",
	"ADJUST_TAGS": "Ajuster les tags",
	"AFFECTEDDEVICES": "appareils concernés par cette règle",
	"AFFECTED_DEVICES": "Appareils concernés",
	"ALARMBYDEVICETYPE": "Alarme par type d'appareil",
	"ALARMED_DEVICE": "Dispositifs alarmés",
	"ALARMED_TELEMETRY": "Télémétrie de l'appareil en alarme",
	"ALARMLOG": "Journal d'alarme",
	"ALARMS": "Alarmes",
	"ALARMSTATUS": "Alarmes système",
	"ALARM_OCCURENCE": "Les occurrences d'alarme",
	"ALL": "Tout",
	"ALLDEVICES": "Tous les dispositifs",
	"APPLIED": "Appliqué",
	"APPLY": "Appliquer",
	"AUTHENTICATIONTYPE": "Type d'identification",
	"AUTOGENERATEKEYS": "Générer automatiquement des clés",
	"AUTOMATIC": "Automatique",
	"AUTO_GENERATED_KEYS": "Générer automatiquement des clés",
	"AVAILABLEACTIONS": "Actions disponibles",
	"AVAILABLE_PROPERTIES": "Propriétés disponibles et valeurs à modifier",
	"AZUREPROJECTNAME": "Aperçu de la surveillance à distance Azure IoT Suite",
	"CANCEL": "Annuler",
	"CANCELLED": "Annulé",
	"CAUTION": "Attention: Vous planifiez une action qui affectera les appareils {0}.",
	"CHANGEDEVICECONFIG": "Modifier la configuration de l'appareil",
	"CHANGESTATUS": "Changer le statut",
	"CHOOSEDEVICES": "Choisissez les appareils",
	"CHOOSETIMERANGE": "Choisissez la plage de temps",
	"CHOOSE_DEVICE_CONFIGURATION": "Choisissez la configuration de l'appareil",
	"CHOOSE_NEW_DEVICES": "Veuillez choisir des appareils avec des méthodes communes",
	"CLICKTOREFRESH": "Cliquez pour actualiser",
	"CLICK_TO_SHOW": "Cliquez ici pour voir le message brut",
	"CLOSE": "Fermer",
	"CLOSED": "FERMÉ",
	"COMING_SOON": "Arrive bientôt",
	"COMPLETED": "Terminé",
	"CONFIGPROPERTIES": "Propriétés de configuration (properties.desired.config. *)",
	"CONFIRM": "Confirmer",
	"CONNECTED": "Connecté",
	"CONTOSO": "Contoso",
	"COPY": "COPIE",
	"COPY_TO_CLIPBOARD": "Copiez toutes les propriétés dans le presse-papiers",
	"COPY_TO_CLIPBOARD_DESCRIPTION": "Copiez une liste de toutes les propriétés et méthodes associées",
	"COUNT": "NON. Dispositifs",
	"CREATE": "Créer",
	"CREATED": "Créé",
	"CREATEDEVICE": "Créer un appareil",
	"CREATEFILTER": "Créer un filtre",
	"CRITICAL": "Critique",
	"CRITICALALARM": "Alarmes critiques",
	"CURRENTDAY": "Jour actuel",
	"CURRENTMONTH": "Mois en cours",
	"CURRENTWEEK": "Cette semaine",
	"DASHBOARD": "Tableau de bord",
	"DASHBOARD_LABEL": "Tableau de bord",
	"DELETE": "Effacer",
	"DELETE_DEVICE": "Supprimer l'appareil",
	"DELETE_DEVICE_DESCRIPTION": "Cette action supprimera définitivement les appareils de la plateforme.",
	"DESCRIPTION": "La description",
	"DEVICECONFIGURATION": "Configuration de l'appareil",
	"DEVICECOUNT": "appareils concernés par cette règle",
	"DEVICEDETAIL": "Détail du périphérique",
	"DEVICEID": "Reference de l'appareil",
	"DEVICELOCATION": "Emplacement du périphérique",
	"DEVICENAME": "Nom de l'appareil",
	"DEVICENUMBER": "Nombre d'appareils",
	"DEVICEORGANIZATION": "Organisation de l'appareil",
	"DEVICES": "Dispositifs",
	"DEVICES_ARE_PROVISIONING": "les périphériques sont en cours de provisionnement ...",
	"DEVICES_TO_PROVISION": "appareils à provisionner",
	"DEVICETYPE": "Type d'appareil",
	"DEVICETYPES": "Types de périphériques",
	"DEVICE_DELETED": "appareils supprimés avec succès!",
	"DEVICE_ID_AFFECTED": "Identifiant de l'appareil affecté",
	"DIAGNOSTICS": "Diagnostics",
	"DIAGNOSTICS_DESCRIPTION": "Informations de diagnostic de l'appareil",
	"DISABLE": "Désactiver",
	"DISABLED": "désactivé",
	"DISABLED_FILTER": "- - - -",
	"DISABLESELECTEDRULE": "Désactiver les règles sélectionnées",
	"DISCONNECTED": "Débranché",
	"DPSTENANT": "DPS Locataire",
	"DROUPDOWNPLACEHOLDER": "Sélectionner",
	"EDIT": "modifier",
	"ENABLE": "Activer",
	"ENABLED": "Activée",
	"ENABLESELECTEDRULE": "Activer les règles sélectionnées",
	"END_TIME": "Heure de fin",
	"ENQUEUED": "Enqueued",
	"ENROLLMENT": "Inscription",
	"ENTERFILTERVALUE": "Entrer la valeur du filtre",
	"ENTERNAMEFORFILTER": "Entrez le nom du filtre",
	"ENTERREPORTED": "Entrez la propriété signalée ou souhaitée, le tag",
	"ENTERRULEDISCRIPTION": "Entrez la description de la règle ...",
	"ENTERRULENAME": "Entrez le nom de la règle ...",
	"ENTERVALUE": "Entrez la valeur ...",
	"ENTER_DEVICE_ID": "Entrez le préfixe Id de l'appareil ...",
	"ENTER_KEYS_MANUALLY": "Entrez les clés manuellement",
	"ENTER_YOUR_KEY": "Entrez votre clé ici ...",
	"EQUALS": "= Égal",
	"EVENT_NAME": "Nom de l'événement",
	"EXPLOREALARM": "Explorer l'alarme",
	"FAILED": "Échoué",
	"FAILED_CAPITAL": "Échoué",
	"FAILED_JOBS": "Échec des travaux",
	"FIELD": "Champ",
	"FILTER": "Filtre",
	"FILTERNAME": "Nom du filtre",
	"FILTERNAMECANNOTBEEMPTY": "Le nom du filtre ne peut pas être vide",
	"FILTERS": "Filtres",
	"FIRMWARE": "Firmware",
	"FIRMWAREVERSION": "Version du firmware",
	"FIRMWARE_OPTION": "Mise à jour du firmware",
	"FIRMWARE_URL": "URI du micrologiciel",
	"FIRMWARE_URL_INPUT_PLACEHOLDER": "Entrer la valeur de l'URI du firmware",
	"GENERATEDEVICEID": "Générer un identifiant pour moi",
	"GROUP": "Groupe",
	"GROUPNAME": "Nom de groupe",
	"GROUPNAMEALREADYEXISTS": "Le nom du groupe existe déjà",
	"IMGDELETE": "Effacer",
	"IMGEDIT": "modifier",
	"IMGSAVE": "sauvegarder",
	"INDIVIDUAL": "Individuel",
	"INFO": "Info",
	"JOBNAME": "Nom du travail",
	"JOB_NAME": "Nom du travail",
	"JOB_NAME_REFERENCE": "Seules les lettres et les chiffres sont autorisés dans le nom du travail",
	"JOB_NAME_INPUT_PLACEHOLDER": "Entrez le nom du travail",
	"KEY": "CLÉ",
	"LASTACTIVITYTIME": "Dernière heure d'activité",
	"LASTCONNECTION": "Dernière connexion",
	"LASTDAY": "Dernier jour",
	"LASTHOUR": "Dernière heure",
	"LASTMONTH": "Le mois dernier",
	"LASTREFRESHED": "dernier actualisé",
	"LASTSTATUSUPDATEDTIME": "Dernière mise à jour du statut",
	"LASTTRIGGER": "Dernier déclencheur",
	"LASTWEEK": "La semaine dernière",
	"LAST_EVENT": "DERNIER ÉVÉNEMENT",
	"LAST_MSG": "Dernier message",
	"LAST_OCCRRENCES": "Dernières occurrences",
	"LAST_REFRESHED": "DERNIER REFRESH",
	"LAST_RETURN_MESSAGE": "Dernier message de retour",
	"LOADING": "Chargement",
	"LOCATION": "Emplacement",
	"MAINTENANCE": "Entretien",
	"MAINTENANCE_SUMMARY": "Résumé de maintenance",
	"MANAGEFILTER": "Gérer les filtres",
	"MANAGEFILTERS": "Gérer les filtres",
	"MANUAL": "Manuel",
	"MANUFACTURER": "Fabricant",
	"MAP_MODAL_CONTENT": "Cette solution a été configurée avec une carte statique. Pour en savoir plus sur l'ajout d'une carte interactive, visitez notre",
	"MAP_MODAL_FAQS": "FAQs",
	"MESSAGE": "Message",
	"METHODS": "Méthodes",
	"METHODS_DESCRIPTION": "Toutes les méthodes disponibles pour l'appareil",
	"METHODS_NOT_AVAILABLE": "Pas de méthodes communes disponibles.",
	"MODELNUMBER": "Numéro de modèle",
	"MORE": "Plus",
	"MULTIPLE": "Plusieurs",
	"NAME": "prénom",
	"NEWDEVICEID": "Reference de l'appareil",
	"NEWGROUP": "(nouveau groupe)",
	"NEWRULE": "Nouvelle règle",
	"NEWTENANT": "Nouveau locataire",
	"NO": "Non",
	"NOOFDEVICES": "NON. Dispositifs",
	"NOTE": "Remarque: Toute modification apportée aux règles s'appliquera uniquement aux futurs événements sur les périphériques concernés.",
	"NOTIFICATIONTYPE": "Type de notification",
	"NOT_ABLE_TO_DELETE": "La suppression de périphériques simulés n'est actuellement pas prise en charge, cette action ne sera effectuée que sur les périphériques physiques.",
	"NOT_COMPLETED": "Pas achevé",
	"NOW": "À présent",
	"NO_AVAILABLE_COMMON_TAGS": "Pas de tags communs disponibles.",
	"NO_DATA": "Pas de données disponibles",
	"NO_OCCURENCES": "Aucun événement sélectionné",
	"NO_OF_DEVICES": "Aucun appareil",
	"NUMBER": "Nombre",
	"NUMBEROFDEVICES": "Nombre d'appareils",
	"OCCURRENCE": "Occurrence",
	"OFFLINE": "Hors ligne",
	"ONLINE": "En ligne",
	"OPEN": "OUVRIR",
	"OPENOCCURRENCES": "Occurrences ouvertes",
	"OPEN_ALARMS": "Ouvrir les alarmes",
	"OPERATION": "Opération",
	"OPERATOR": "Opérateur",
	"ORGANIZEMYDEVICE": "Organiser mes appareils",
	"PHYSICAL": "Physique",
	"PLEASE_CHOOSE_DEVICES_WITH_COMMON_TAGS": "Veuillez choisir des appareils avec des tags communs",
	"PREVIEWNOTICE": "Remarque: Cette solution de surveillance à distance est en mode de prévisualisation et des fonctionnalités supplémentaires seront ajoutées dans les semaines à venir. Cliquez ici pour en savoir plus sur ce qui arrive bientôt!",
	"PRIMARYKEY": "Clé primaire",
	"PRIMARYTHUMBPRINT": "Empreinte primaire",
	"PROPERTIES": "Propriétés",
	"PROPERTIES_DESCRIPTION": "Propriétés sélectionnées sur les appareils",
	"PROPERTYNAME": "prénom",
	"PROPERTYTYPE": "Type",
	"PROPERTYVALUE": "Valeur",
	"PROVISIONDEVICES": "Disposition",
	"PROVISION_LOADING": "Chargement...",
	"PROVISION_SUMMARY": "Résumé de la provision",
	"QUEUED": "En file d'attente",
	"RECONFIGURE": "Reconfigurer",
	"RECONFIGURE_JOB": "ReconfigureJob",
	"REGION": "Région",
	"RELATED_INFO": "Informations connexes",
	"RELEVANTSTORAGEINFO": "Informations de stockage pertinentes",
	"REMOVECONDITIONS": "Supprimer les conditions",
	"RULEDETAIL": "Détail de la règle",
	"RULENAME": "Nom de la règle",
	"RULESTATUS": "Statut de la règle",
	"RULES_ACTIONS": "Règles et Actions",
	"RULE_DETAIL": "Détail de la règle",
	"RULE_NAME": "Nom de la règle",
	"RULE_SUBTITLE": "Gérez les occurrences d'alarme associées à cette règle dans la section ci-dessous et utilisez les informations associées pour résoudre chaque occurrence.",
	"RUNNING": "Fonctionnement",
	"SAVE": "sauvegarder",
	"SCHEDULE": "Programme",
	"SCHEDULEANACTION": "Programmer une action",
	"SCHEDULED": "Prévu",
	"SECONDARYKEY": "Clé secondaire",
	"SECURESTORAGETYPE": "Type de stockage sécurisé",
	"SELECTDEVICEGROUP": "Sélectionnez le groupe de périphériques de règles ...",
	"SELECTMETHOD": "Sélectionnez votre méthode de provisionnement",
	"SELECTTIMELINE": "Sélectionnez la ligne de temps",
	"SELECTTYPE": "Sélectionnez un type d'appareil existant",
	"SELECT_EXISTING_DVICE_TYPE": "Sélectionnez le type d'appareil existant",
	"SELECT_ONE": "Sélectionnez un",
	"SELECT_PLACEHOLDER": "Sélectionnez la méthode",
	"SENCONDARYTHUMBPRINT": "Empreinte secondaire",
	"SEVERITY": "Gravité",
	"SEVERITYLEVEL": "Degré de gravité",
	"SIMULATED": "Simulé",
	"SIMULATEDDEVICES": "Appareil (s) simulé (s)",
	"SIMULATION_DATA": "Données de simulation",
	"SIMULATION_SETTINGS_DESC": "Démarrer ou arrêter la simulation des appareils. La simulation de l'arrêt du dispositif minimisera le coût de la solution. aucune télémétrie simulée ne sera envoyée à votre IoTHub et aucune alarme ne sera générée pour les appareils simulés.",
	"SIM_CONTROL_CENTER": "Centre de contrôle SIM",
	"SOURCE": "La source",
	"SOURCEHELP": "Modifier le groupe de périphériques sur la règle",
	"START": "Début",
	"START_TIME": "Heure de début",
	"STATE": "Etat",
	"STATUS": "Statut",
	"STOP": "Arrêtez",
	"STOPPED": "Arrêté",
	"STRING": "Chaîne",
	"SUCCEEDED": "Réussi",
	"SUCCEEDED_CAPITAL": "Réussi",
	"SUMMARY": "Résumé",
	"SWITCHUSER": "Passer à un autre utilisateur",
	"SYMMETRICKEY": "Clé symétrique",
	"SYMMETRIC_KEY": "Clé symétrique",
	"SYNCING": "Synchronisation",
	"SYSTEMKPI": "KPI du système",
	"SYSTEM_GENERATED_DEVICE_ID": "ID de périphérique générés par le système",
	"SYSTEM_STATUS": "État du système",
	"TAG": "Marque",
	"TAGS": "Mots clés",
	"TAGS_DESCRIPTION": "Tags appliqués à l'appareil",
	"TAGS_IN_COMMON_SELECTED_DEVICE": "Tags dans l'appareil sélectionné commun",
	"TAGS_ON_SELECTED_DEVICES": "Tags sur les appareils sélectionnés",
	"TASKNAME": "Nom de la tâche",
	"TELEMETRY": "Télémétrie",
	"TH_ACTIONS": "ACTES",
	"TH_FIELD": "CHAMP",
	"TH_OPERATOR": "OPÉRATEUR",
	"TH_VALUE": "VALEUR",
	"TIME": "Temps",
	"TIMERANGE": "INTERVALLE DE TEMPS",
	"TIMEWINDOW": "Fenêtre de temps",
	"TOPRULESTRIGGERED": "Principales règles déclenchées",
	"TOTAL": "Total",
	"TOTAL_COUNT": "Le compte total",
	"TRIGGER": "Déclencheur",
	"TRIGGER_DEVICE": "Déclencheur",
	"TYPE": "Type",
	"UNKNOWN_ERROR": "Oups, nous avons rencontré une erreur inconnue",
	"UPDATE": "Mettre à jour",
	"VALUE": "Valeur",
	"VALUECANNOTBEEMPTY": "La valeur ne peut pas être vide",
	"VERSION": "Version",
	"VIEW": "Vue",
	"VIEW_JOB_STATUS": "Afficher la progression de l'état d'un travail dans la page Maintenance",
	"WARNING": "Attention",
	"WARNINGS": "Avertissements",
	"X509": "X.509",
	"YES": "Oui"
};

export default lang;
